### ISSUE TITLE
ModuleNotFoundError: No module named 'openai.error'

### ISSUE THREAD

**Issue by Pitaya0118** [ElmiraGhorbani/chatgpt-long-term-memory#1]
I've installed openai but the error showed up.   please help me
![螢幕擷取畫面 2023-11-07 193329](https://github.com/ElmiraGhorbani/chatgpt-long-term-memory/assets/147990451/ab1bc599-701c-4e46-adc2-934a9f2dae1d)

**Comment by ElmiraGhorbani** [comment]
In your python env just install ```pip install chatgpt_long_term_memory```

**Comment by Pitaya0118** [comment]
I have installed befrore and tried to reinstall (by pip install chatgpt_long_term_memory command)
I also tried to restart my pc and visual studio,  but it  didn't work.
![螢幕擷取畫面 2023-11-07 212536](https://github.com/ElmiraGhorbani/chatgpt-long-term-memory/assets/147990451/2a319297-8b44-4986-ae0f-6f05dad130e6)
![Uploading 螢幕擷取畫面 2023-11-07 212619.png…]()

**Comment by ElmiraGhorbani** [comment]
Create a new python environment or try :
```
pip uninstall openai
pip install openai>=0.27.8
```
[
<img width="1182" alt="Screenshot 2023-11-08 at 9 19 20 AM" src="https://github.com/ElmiraGhorbani/chatgpt-long-term-memory/assets/23237541/20b18284-cc5a-4c05-b97d-00f28f92ebbd">
](url)
